server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.link}
    username: ${db.username}
    password: ${db.password}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ims.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

google:
  maps:
    api-key: ${gmaps.api-key}