spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev
#    url: jdbc:mysql://google/coms4156?cloudSqlInstance=coms4156-402215:us-central1:iheartapi&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: root
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl