name: "Build & analysis & testing"

on:
  push:
    branches:
      - main

jobs:
  setup-build:
    if: github.repository == 'shiy9/4156_F23_Project'
    name: Setup, Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          server-id: github
          distribution: 'adopt'
          settings-path: ${{ github.workspace }}


      - name: Build with Maven
        run: mvn -B package --file ims/pom.xml
        env:
          DBLINK: ${{ secrets.DBLINK }}
          DBUSERNAME: ${{ secrets.DBUSERNAME }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          GMAPSAPIKEY: ${{ secrets.GMAPSAPIKEY }}
          TOKENSECRETKEY: ${{ secrets.TOKENSECRETKEY }}

      - name: Run Unit tests & Integration tests
        run: mvn -B test --file ims/pom.xml
        env:
          DBLINK: ${{ secrets.DBLINK }}
          DBUSERNAME: ${{ secrets.DBUSERNAME }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          GMAPSAPIKEY: ${{ secrets.GMAPSAPIKEY }}
          TOKENSECRETKEY: ${{ secrets.TOKENSECRETKEY }}

      - name: Verify
        run: mvn -B verify --file ims/pom.xml
        env:
          DBLINK: ${{ secrets.DBLINK }}
          DBUSERNAME: ${{ secrets.DBUSERNAME }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          GMAPSAPIKEY: ${{ secrets.GMAPSAPIKEY }}
          TOKENSECRETKEY: ${{ secrets.TOKENSECRETKEY }}    

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: ims/target/site/jacoco/ # Adjust to your project structure


  codeql-analysis:
    needs: setup-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
